// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// baycast_cpp
Rcpp::List baycast_cpp(const arma::vec& Y, const arma::vec& logC, const arma::mat& X, const arma::mat& W, const arma::vec& b0_beta, const arma::mat& B0_beta, double mu0, double kappa_mu0, double a0, double b0, int d, int K_max, int K_init, int iters, int burn, int thin, double sigmaA2, double tau_spike2, double pi0, double alpha_fixed, double alpha_init, double a_alpha, double b_alpha, bool sample_ab, double alpha_a_prior, double beta_a_prior, double alpha_b_prior, double beta_b_prior, double mh_a_sd, bool init_A_pca, bool init_z_kmeans, bool ind_slice, double rho, double nu_w_prior, const IntegerVector& diag_feat_idx, int diag_max_keep);
RcppExport SEXP _BayCAST_baycast_cpp(SEXP YSEXP, SEXP logCSEXP, SEXP XSEXP, SEXP WSEXP, SEXP b0_betaSEXP, SEXP B0_betaSEXP, SEXP mu0SEXP, SEXP kappa_mu0SEXP, SEXP a0SEXP, SEXP b0SEXP, SEXP dSEXP, SEXP K_maxSEXP, SEXP K_initSEXP, SEXP itersSEXP, SEXP burnSEXP, SEXP thinSEXP, SEXP sigmaA2SEXP, SEXP tau_spike2SEXP, SEXP pi0SEXP, SEXP alpha_fixedSEXP, SEXP alpha_initSEXP, SEXP a_alphaSEXP, SEXP b_alphaSEXP, SEXP sample_abSEXP, SEXP alpha_a_priorSEXP, SEXP beta_a_priorSEXP, SEXP alpha_b_priorSEXP, SEXP beta_b_priorSEXP, SEXP mh_a_sdSEXP, SEXP init_A_pcaSEXP, SEXP init_z_kmeansSEXP, SEXP ind_sliceSEXP, SEXP rhoSEXP, SEXP nu_w_priorSEXP, SEXP diag_feat_idxSEXP, SEXP diag_max_keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type logC(logCSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type b0_beta(b0_betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B0_beta(B0_betaSEXP);
    Rcpp::traits::input_parameter< double >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< double >::type kappa_mu0(kappa_mu0SEXP);
    Rcpp::traits::input_parameter< double >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< double >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< int >::type K_max(K_maxSEXP);
    Rcpp::traits::input_parameter< int >::type K_init(K_initSEXP);
    Rcpp::traits::input_parameter< int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaA2(sigmaA2SEXP);
    Rcpp::traits::input_parameter< double >::type tau_spike2(tau_spike2SEXP);
    Rcpp::traits::input_parameter< double >::type pi0(pi0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_fixed(alpha_fixedSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< double >::type a_alpha(a_alphaSEXP);
    Rcpp::traits::input_parameter< double >::type b_alpha(b_alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type sample_ab(sample_abSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_a_prior(alpha_a_priorSEXP);
    Rcpp::traits::input_parameter< double >::type beta_a_prior(beta_a_priorSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_b_prior(alpha_b_priorSEXP);
    Rcpp::traits::input_parameter< double >::type beta_b_prior(beta_b_priorSEXP);
    Rcpp::traits::input_parameter< double >::type mh_a_sd(mh_a_sdSEXP);
    Rcpp::traits::input_parameter< bool >::type init_A_pca(init_A_pcaSEXP);
    Rcpp::traits::input_parameter< bool >::type init_z_kmeans(init_z_kmeansSEXP);
    Rcpp::traits::input_parameter< bool >::type ind_slice(ind_sliceSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type nu_w_prior(nu_w_priorSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type diag_feat_idx(diag_feat_idxSEXP);
    Rcpp::traits::input_parameter< int >::type diag_max_keep(diag_max_keepSEXP);
    rcpp_result_gen = Rcpp::wrap(baycast_cpp(Y, logC, X, W, b0_beta, B0_beta, mu0, kappa_mu0, a0, b0, d, K_max, K_init, iters, burn, thin, sigmaA2, tau_spike2, pi0, alpha_fixed, alpha_init, a_alpha, b_alpha, sample_ab, alpha_a_prior, beta_a_prior, alpha_b_prior, beta_b_prior, mh_a_sd, init_A_pca, init_z_kmeans, ind_slice, rho, nu_w_prior, diag_feat_idx, diag_max_keep));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BayCAST_baycast_cpp", (DL_FUNC) &_BayCAST_baycast_cpp, 36},
    {NULL, NULL, 0}
};

RcppExport void R_init_BayCAST(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
