# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bdpaft_cpp <- function(Y, logC, X, W, b0_beta, B0_beta, mu0, kappa_mu0, a0, b0, d, K_max, K_init, iters, burn, thin, sigmaA2, pi0, alpha_fixed, alpha_init, a_alpha, b_alpha, sample_ab, alpha_a_prior, beta_a_prior, alpha_b_prior, beta_b_prior, mh_a_sd, init_A_pca, init_z_kmeans, ind_slice, rho, nu_w_prior, diag_feat_idx, diag_max_keep) {
    .Call(`_bdpaft_bdpaft_cpp`, Y, logC, X, W, b0_beta, B0_beta, mu0, kappa_mu0, a0, b0, d, K_max, K_init, iters, burn, thin, sigmaA2, pi0, alpha_fixed, alpha_init, a_alpha, b_alpha, sample_ab, alpha_a_prior, beta_a_prior, alpha_b_prior, beta_b_prior, mh_a_sd, init_A_pca, init_z_kmeans, ind_slice, rho, nu_w_prior, diag_feat_idx, diag_max_keep)
}

